const RESPONSE_CODE = {
    SUCESS: 200,
    UNPROCESSABLE_REEQUEST: 422
}

const USER_DISCOUNT_IN_PER = 20;

const BONUS_MAX_PER_USE = 10;

module.exports = {
    RESPONSE_CODE,
    USER_DISCOUNT_IN_PER,
    BONUS_MAX_PER_USE
}